export const ErrorCodes = {
  BAD_REQUEST: "BAD_REQUEST",
  INVALID_ADDRESS: "INVALID_ADDRESS",
  INDEXER_UNAVAILABLE: "INDEXER_UNAVAILABLE",
  INDEXER_STALE: "INDEXER_STALE",
  CHAIN_READ_FAILED: "CHAIN_READ_FAILED",
  PASS_REQUIRED: "PASS_REQUIRED",
  PASS_ALREADY_OWNED: "PASS_ALREADY_OWNED",
  ROUND_NOT_FOUND: "ROUND_NOT_FOUND",
  ROUND_NOT_JOINABLE: "ROUND_NOT_JOINABLE",
  ALREADY_JOINED: "ALREADY_JOINED",
  NOTHING_TO_CLAIM: "NOTHING_TO_CLAIM",
  TX_BUILD_FAILED: "TX_BUILD_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
